### PR TITLE
Limit decoded images to 2^26 pixels by default

### LINKED ISSUE #80: Unbounded memory consumption on malformed inputs
There is an integer overflow in https://github.com/PistonDevelopers/image-png/blob/99383650e1a440bb14c54987938676c8f54d3bc6/src/decoder/mod.rs#L51

Aside of posing dangers for unsafe code (which shouldn't rely on this value anyway), this overflow causes enormous amounts of memory to be _actually_ allocated when fed to `png` crate via the [fuzzing harness](https://github.com/Shnatsel/image-png/blob/master/png-afl/src/main.rs). Not just virtual memory - actual physical memory.

The worst part is, fixing this correctly requires changing the external API: the function should use [checked_mul()](https://doc.rust-lang.org/std/primitive.usize.html#method.checked_mul) which returns `Option<usize>`, and actually return either an Option or Result to the outside.

Testcase: [integer_overflow_in_multiplication](https://user-images.githubusercontent.com/291257/41970114-4dcd90f6-7a12-11e8-9393-03251e376dc4.png) found via [afl-rs](https://github.com/rust-fuzz/afl.rs). Steps to reproduce the crash can be found in #79 except you need to build in debug mode, without the `--release` flag.

I would appreciate advice on how to proceed with fixing this issue. Is adding "deprecated" marker to this function in 0.12 series and releasing 0.13 with a breaking fix appropriate? Do we need the [semver trick](https://github.com/dtolnay/semver-trick) here?

**Update:** libpng itself also had similar issues; see https://libpng.sourceforge.io/decompression_bombs.html for more info. Among other things, they have introduced limits on the possible size of an image by default. In Rust we can easily allow the API user to override these limits via the [builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html).

### PR DESCRIPTION
**Pull request by zealousidealroll**
Fixes #80

### CODE REVIEW

**Comment by bvssvni** [comment]
Looks good to me.

**Comment by HeroicKatora** [comment]
The limit appears somewhat arbitrary to me. Is it referring to a limit already established in another library?

**Comment by HeroicKatora** [comment]
Considering that it triggers on a quadratic image of width and length each `2^13 = 8192` which is already well in range of some of the better cameras and might even become a monitor resolution in the foreseeable future. For example, IMAX is [estimated at just about 10000x7000 according to Wikipedia](https://en.wikipedia.org/wiki/Image_resolution). And Japan wants to record the 2020 olympics in [16k resolution](https://en.wikipedia.org/wiki/16K_resolution).

**Comment by oyvindln** [comment]
In the BMP decoder in image there is a [max](https://github.com/PistonDevelopers/image/blob/master/src/bmp/decoder.rs#L53) of ``2^16``, though one may not expect bmp images to be quite as large as a png image (as they are not, or only very slightly compressed). 

There is also a limit on how much memory the decoder allocates at a first try, and it will only allocate more if there is actually image data for it. Maybe something similar could be done here.

Ideally though it would be nice if a limit could be specified, so the caller could say give some reasonable expected max size based on say the file size.

**Comment by HeroicKatora** [comment]
The max in BMP is enforced for width and height individually, so in total limit the size to something slightly smaller than 2^32. The limit proposed here is for the actual pixel count, `width*height`.

**Comment by oyvindln** [comment]
Yeah I meant to write ``2^16`` in one direction but I somehow missed it.

**Comment by zealousidealroll** [comment]
The limit was copied from the [flif](https://github.com/dgriffen/flif.rs) crate.

**Comment by HeroicKatora** [comment]
Ah, I didn't realize that. [In the corresponding pull request](https://github.com/dgriffen/flif.rs/pull/28), the choice was explained as follows:

> Default values allow maximum size of DecodingImage's data equal to 2^26, which is equal to 512 MB.

Now I wonder if we should differentiate between a pixel and a memory limit. `png` allows bit depths of up to 16 bit and up to 4 samples per pixel, leading to up to `16=2^4` bytes per pixel in the most extreme case. Setting a limit on the number of pixels would enforce somewhere between `32MiBi` and `1024MiBi` of memory usage, depending on the colour format.

However, that is more of a bikeshedding issue for now, with prior art demonstrated it might be sensible to just merge it for now. Increasing the default limit in the future or adding alternative and optional additional limits should not be a breaking change anyways.

File: src/decoder/mod.rs [hunk 1]
```diff
@@ -53,23 +53,67 @@ impl OutputInfo {
     }
 }
 
+#[derive(Clone, Copy, Debug)]
+pub struct Limits {
+    /// max number of pixels: `width * height` (default: 67M = 2<sup>26</sup>)
+    pixels: u64,
+}
```
Comment (newpavlov) [inline src/decoder/mod.rs]: I think there shouldn't be any problems with making `pixels` field public. This will also allow us to remove `set_pixels` setter.

File: src/decoder/mod.rs [hunk 2]
```diff
@@ -53,23 +53,67 @@ impl OutputInfo {
...
+    /// assert!(decoder.read_info().is_err());
+    /// // This image is 32x32 pixels, so it's exactly 1024 pixels in size.
+    /// let mut limits = Limits::default();
+    /// limits.set_pixels(1024);
+    /// let mut decoder = Decoder::new(File::open("tests/pngsuite/basi0g01.png").unwrap());
+    /// decoder.set_limits(limits);
+    /// assert!(decoder.read_info().is_ok());
+    /// ```
+    pub fn set_limits(&mut self, limits: Limits) {
+        self.limits = limits;
```
Comment (newpavlov) [inline src/decoder/mod.rs]: How about using `new_with_limits(r: R, limits: Limits)` method instead? It will allow to create decoder in one line and `new` can be defined as `Self::new_with_limits(r, Default::default())`.

**Comment by Shnatsel** [comment]
For reference, libpng enforces 1,000,000 by 1,000,000 pixels limit by default, which is roughly 2^40 pixels or 2^44 bytes per image in the extreme case.

**Comment by zealousidealroll** [comment]
> 2^40 pixels

* Even with a measly 256 colors (so it would be 2^40 bytes), that's bigger than the entire address space on a 32-bit system. If nothing else, the limits should never be higher than 2^29 on a 32-bit system (making 2^31 bytes at 2^2=4 bytes per pixel, which will exactly fill the userland-accessible address space on a 32-bit system where the upper half is reserved for the operating system). If you think anyone's ever going to need higher, then make it conditional on the platform.

* According to my quick Wikipedia visit, an [8K picture](https://en.wikipedia.org/wiki/8K_resolution) is [2^25 pixels](https://duckduckgo.com/?q=log(7680*4320)+%2F+log(2)&t=ffab&ia=calculator). In the immortal words of Bill Gates, 8K should be enough for anybody.

**Comment by bvssvni** [comment]
Merging.
